language: php
php:
  - 7.3
  - 7.2
  - 7.1
  - 7.0

before_script:
  - composer self-update
  - composer install

script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.clover
  - ./vendor/bin/test-reporter --coverage-report=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

sudo: false
